name: environment
favicon: null
layout_spectrum: 0.5171316389460117
typography_spectrum: 0.7208213615231216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.34542710171081126
  lightness: 0.9984449970070273
  saturation: 0.033198015531525016
  rhythmicContrast: 0.6519291584845632
purpose: []
